services:
    aaronadal.config.twig:
        class: Aaronadal\ConfigBundle\TwigExtension
        public: false
        arguments:
            - "@=service('service_container').getParameterBag()"
        tags:
            - name: twig.extension
